name: Glicocheck Github Continuos Integration
on: push
jobs:
  build-node:
    name: Build and run Node project
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - run: node --version
        name: Check Node version
      - run: npm --version
        name: Check NPM version
      - uses: actions/checkout@v3
        name: Check out code from Github
      - run: npm install
        name: Install Npm packages
      - run: npm run dev
        name: Run Node application