name: pre-push
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    name: Static code analysis with Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install the dependencies
        run: npm i
      - name: It runs the linter
        run: npm run lint