name: Integration tests
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    name: Execute integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install the dependencies
        run: npm i
      - name: Run the tests
        run: npm test